version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependecies-{{ checksum "requirements.txt" }}
            - v1-dependecies-
      - run:
          name: install deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependecies-{{ checksum "requirements.txt" }}
    
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
